name: Build and push docker image to GCR
description: |
  Build and Push Docker image to GCR
inputs:
  image-name:
    required: true
    description: Name of Docker image

  image-tag:
    required: true
    description: Tag of Docker image

  gcloud-secrets:
    required: false
    description: Content of GCP service account json

  gcloud-project-id:
    required: false
    description: GCP project ID

  gcloud-registry:
    required: false
    description: GCR registry url

  dockerfile:
    required: false
    description: Dockerfile path
    default: Dockerfile
  
  docker-context:
    required: false
    description: Docker build context
    default: .

  docker-additionals:
    require: false
    description: Docker build additional commands
    default: ""

  push:
    required: false
    description: Push or not
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker Image For Testing
      if: ${{ inputs.push }} == 'false'
      run: |
        docker build --tag ${{ inputs.image-name }}:${{inputs.image-tag }} ${{ inputs.docker-additionals }} --file ${{ inputs.dockerfile }}	${{ inputs.docker-context }}
      shell: bash

    - name: Build Docker Image With Tag
      if: ${{ inputs.push }} == 'true'
      id: builder
      run: |
        docker build --tag ${{ inputs.gcloud-registry}}/${{ inputs.gcloud-project-id }}/${{ inputs.image-name }}:${{inputs.image-tag }} ${{ inputs.docker-additionals }} --file ${{ inputs.dockerfile }}	${{ inputs.docker-context }}
      shell: bash

    - uses: google-github-actions/auth@v2
      if: ${{ inputs.push }} == 'true'
      with:
        credentials_json: '${{ inputs.gcloud-secrets }}'

    - name: Set up Cloud SDK
      if: ${{ inputs.push }} == 'true'
      uses: google-github-actions/setup-gcloud@v2
  
    - name: Configure Docker for GCR
      if: ${{ inputs.push }} == 'true'
      run: |
        gcloud auth configure-docker ${{ inputs.gcloud-registry }}
      shell: bash

    - name: Push Docker Image to Google Cloud Registry
      if: ${{ inputs.push }} == 'true'
      run: |
        docker push ${{ inputs.gcloud-registry}}/${{ inputs.gcloud-project-id }}/${{ inputs.image-name }}:${{inputs.image-tag }}
      shell: bash
