name: Update image tag
description: |
  Update image tag using yq
inputs:
  repo:
    required: true
    description: Name of Docker image

  github-token:
    required: true
    description: Tag of Docker image

  values-file:
    required: true
    description: Path to values file

  xpath:
    required: true
    description: Image tag Xpath

  tag:
    required: true
    description: New image Tag

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.github-token }}
    - name: Get an entry with a variable that might contain dots or spaces
      id: get_username
      uses: mikefarah/yq@v4.42.1
      with:
        cmd: yq e '${{ inputs.xpath }} = "${{ inputs.tag }}"' -i ${{ inputs.values-file }}

    - name: Push changes to gitops
      run: |
        echo Pushing changes to ${{ inputs.repo }}
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --all
        git commit --allow-empty -m "Deploy \"${{ inputs.tag }}\" tag into ${{ inputs.values-file }}"
        git pull --rebase
        git push -u origin master
      shell: bash
