name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  yaml:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install yamllint

      - name: Lint YAML files in directory and subdirectories
        run: yamllint . -c .yamllint